---
version: 2
project_name: node
dist: ./.cache/goreleaser/main
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - apt update
    - apt install -y pkg-config libudev-dev:amd64 libudev-dev:arm64
builds:
  - id: akt-darwin-amd64
    binary: akt
    main: ./cmd/akt
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_CFLAGS=-mmacosx-version-min=10.12
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -mmacosx-version-min=10.12"
  - id: akt-darwin-arm64
    binary: akt
    main: ./cmd/akt
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_CFLAGS=-mmacosx-version-min=10.12
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -mmacosx-version-min=10.12"
  - id: akt-linux-amd64
    binary: akt
    main: ./cmd/akt
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      # yamllint disable-line rule:line-length
      - -extldflags "-L./.cache/lib -Wl,-z,muldefs -lm -lrt -lc"
  - id: akt-linux-arm64
    binary: akt
    main: ./cmd/akt
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      # yamllint disable-line rule:line-length
      - -extldflags "-L./.cache/lib -Wl,-z,muldefs -lm -lrt -lc"
universal_binaries:
  - id: akt-darwin-universal
    ids:
      - akt-darwin-amd64
      - akt-darwin-arm64
    replace: true
    name_template: "akt"
archives:
  - id: w/version
    ids:
      - akt-darwin-universal
      - akt-linux-amd64
      - akt-linux-arm64
    name_template: "akt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    formats:
      - zip
    files:
      - none*
  - id: wo/version
    ids:
      - akt-darwin-universal
      - akt-linux-amd64
      - akt-linux-arm64
    name_template: "akt_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    formats:
      - zip
    files:
      - none*

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "akt_checksums.txt"

nfpms:
  - id: w/version
    vendor: "Akash Network"
    homepage: "https://akash.network"
    maintainer: "Akash Network <hello@akash.network>"
    file_name_template: "akt_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    license: Apache 2.0
  - id: wo/version
    vendor: "Akash Network"
    homepage: "https://akash.network"
    maintainer: "Akash Network <hello@akash.network>"
    file_name_template: "akt_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: akash-network
    name: akt
  prerelease: auto
  mode: replace
  draft: false
