package cli

import (
	"testing"

	wasmtypes "github.com/CosmWasm/wasmd/x/wasm/types"
)

// TestBuildAddressPredictable pins the derivation against a vector produced by
// wasmd's keeper.BuildAddressPredictable, which this replaced.
//
// The address is consensus-relevant: it must match what the chain computes, so
// a drift here is not a cosmetic difference. The vector was generated by
// calling wasmd's keeper.BuildAddressPredictable directly with these inputs,
// and must not change on a wasmd bump unless wasmd changes the derivation.
func TestBuildAddressPredictable(t *testing.T) {
	const (
		codeHash = "B97763A6116D2EAAD99D96DE83B5FFABF4CC5DD927CA3E426AC02C767902162A"
		creator  = "akash10d07y265gmmuvt4z0w9aw880jnsr700jhe7z0f"
		salt     = "6162"
		want     = "akash1m0330femfr9nwea5uj4p00snn64xgfyyz79uf54w2xxzxvwxawxqj6hqt0"
	)

	got, err := buildAddressPredictable(&wasmtypes.QueryBuildAddressRequest{
		CodeHash:       codeHash,
		CreatorAddress: creator,
		Salt:           salt,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if got.Address != want {
		t.Fatalf("address drifted from wasmd:\n got %s\nwant %s", got.Address, want)
	}
}

// TestBuildAddressPredictableRejects covers the argument errors, which wasmd
// reaches by panicking in places. A CLI should report them.
func TestBuildAddressPredictableRejects(t *testing.T) {
	const (
		codeHash = "B97763A6116D2EAAD99D96DE83B5FFABF4CC5DD927CA3E426AC02C767902162A"
		creator  = "akash10d07y265gmmuvt4z0w9aw880jnsr700jhe7z0f"
	)

	tests := []struct {
		name string
		req  *wasmtypes.QueryBuildAddressRequest
	}{
		{"nil request", nil},
		{"empty salt", &wasmtypes.QueryBuildAddressRequest{CodeHash: codeHash, CreatorAddress: creator, Salt: ""}},
		{"odd-length salt", &wasmtypes.QueryBuildAddressRequest{CodeHash: codeHash, CreatorAddress: creator, Salt: "abc"}},
		{"bad code hash", &wasmtypes.QueryBuildAddressRequest{CodeHash: "zz", CreatorAddress: creator, Salt: "6162"}},
		{"bad creator", &wasmtypes.QueryBuildAddressRequest{CodeHash: codeHash, CreatorAddress: "not-an-address", Salt: "6162"}},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := buildAddressPredictable(tc.req); err == nil {
				t.Fatal("expected an error")
			}
		})
	}
}
