accounts:
- name: accountone
  address: akash1ggk74pf9avxh3llu30yfhmr345h2yrpf7c2cdu
  type: Standard
profiles:
- name: Profile1
  account: accountone
  network: akash
networks:
- name: akash
  chainid: ""
  endpoints:
  - name: Primary
    type: RPC
    uri: https://rpc.akashnet.net:443
  fees: "200000"
  gasprices: ""
